-- Add AI Analysis Columns to Educational Activities Table
-- Run this in Supabase SQL Editor

-- Add learning_assessment column for quality analysis
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS learning_assessment JSONB;

-- Add ai_analysis column for AI agent analysis data
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS ai_analysis JSONB;

-- Add ai_recommendations column for AI-generated recommendations
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS ai_recommendations JSONB;

-- Add ai_confidence_score column for AI confidence tracking
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS ai_confidence_score DECIMAL(3,2) DEFAULT 0.75;

-- Add concepts_covered column if it doesn't exist
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS concepts_covered JSONB;

-- Add session_id column for Zep memory tracking
ALTER TABLE educational_activities 
ADD COLUMN IF NOT EXISTS session_id VARCHAR(255);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_educational_activities_ai_analysis 
ON educational_activities USING GIN (ai_analysis);

CREATE INDEX IF NOT EXISTS idx_educational_activities_learning_assessment 
ON educational_activities USING GIN (learning_assessment);

CREATE INDEX IF NOT EXISTS idx_educational_activities_ai_recommendations 
ON educational_activities USING GIN (ai_recommendations);

CREATE INDEX IF NOT EXISTS idx_educational_activities_session_id 
ON educational_activities (session_id);

CREATE INDEX IF NOT EXISTS idx_educational_activities_ai_confidence 
ON educational_activities (ai_confidence_score);

-- Add comments for documentation
COMMENT ON COLUMN educational_activities.learning_assessment IS 'AI-powered learning quality assessment with depth analysis';
COMMENT ON COLUMN educational_activities.ai_analysis IS 'Complete AI agent analysis including tool results and reasoning';
COMMENT ON COLUMN educational_activities.ai_recommendations IS 'Personalized learning recommendations generated by AI';
COMMENT ON COLUMN educational_activities.ai_confidence_score IS 'AI confidence score (0.0-1.0) for analysis quality';
COMMENT ON COLUMN educational_activities.concepts_covered IS 'Agricultural concepts extracted from activity content';
COMMENT ON COLUMN educational_activities.session_id IS 'Zep memory session identifier for context tracking';